CREATE DATABASE SpMedGroup_Manha;

USE  SpMedGroup_Manha;

CREATE TABLE Clinica (
IdClinica  INT PRIMARY KEY IDENTITY,
RazaoSocial  VARCHAR(200) NOT NULL ,
Endereco    VARCHAR(200) NOT NULL,
CNPJ        VARCHAR(50)  NOT NULL,
HorarioFuncionamento  VARCHAR(200)
);


CREATE TABLE TipoUsuario (
IdTipoUsuario  INT PRIMARY KEY IDENTITY,
TituloTipoUsuario   VARCHAR(200) NOT NULL
);


CREATE TABLE Especialidade(
IdEspecialidade   INT PRIMARY KEY IDENTITY,
Titulo VARCHAR(200) NOT NULL
);

CREATE TABLE Usuario(
IdUsuario INT PRIMARY KEY IDENTITY,
IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
Nome    VARCHAR(200) NOT NULL,
Email   VARCHAR(150) NOT NULL UNIQUE,
Senha   VARCHAR (150) NOT NULL 
);

CREATE TABLE Paciente(
IdPaciente INT PRIMARY KEY IDENTITY,
IdUsuario  INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
DataNascimento DATE NOT NULL,
Telefone  VARCHAR(100) NOT NULL UNIQUE,
RG        VARCHAR(50) NOT NULL UNIQUE,
Endereco  VARCHAR(200) ,
CPF       VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Medico(
IdMedico   INT PRIMARY KEY IDENTITY,
IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) ,
IdEspecialidade  INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade),
CRM   VARCHAR(200)  NOT NULL UNIQUE
);



CREATE TABLE Situacao(
IdSituacao INT PRIMARY KEY IDENTITY,
Titulo  VARCHAR(200) NOT NULL
);

CREATE TABLE Consulta (
IdConsulta   INT PRIMARY KEY IDENTITY,
IdMedico  INT FOREIGN KEY REFERENCES Medico(IdMedico),
IdPaciente  INT FOREIGN KEY REFERENCES Paciente(IdPaciente),
IdSituacao  INT FOREIGN KEY REFERENCES Situacao(IdSituacao),
Descricao   VARCHAR(200),
DataConsulta  DATETIME2
);





SELECT * FROM Clinica;
SELECT * FROM TipoUsuario;
SELECT * FROM Especialidade;
SELECT * FROM Usuario;
SELECT * FROM Paciente;
SELECT * FROM Medico;
SELECT * FROM Situacao;
SELECT * FROM Consulta;

